# --- Production Database (Injected via Environment Variables) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- Prod JPA (Strict Safety) ---
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# --- Flyway Prod ---


spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none


# --- Production Secrets ---
app.jwt.secret=${JWT_SECRET}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# --- Swagger/OpenAPI (DISABLED for Security) ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# --- Prod Logging (Performance optimized) ---
logging.level.org.flywaydb=DEBUG
logging.level.root=INFO
logging.level.com.codegravity.itconsultancy=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# CORS - Production
cors.allowed-origins[0]=https://yourapp.com
cors.allowed-origins[1]=https://d1nt0kcjmct67k.cloudfront.net/